base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  # Robot Configuration parameters
  acc_lim_x: 3.0 #2.5 meters/sec^2
  acc_lim_y: 3.0 #2.5
  acc_lim_theta: 3.0 #3.2

  max_vel_trans: 5.0 #0.5
  min_vel_trans: -5.0 #0.1

  max_vel_x: 0 #0.5
  min_vel_x: 0 #0.5

  max_vel_theta: 10.0 #1.0
  min_vel_theta: -10.0 #-1.0

  max_vel_y: 5 #0.1
  min_vel_y: 0 #-0.1

  max_rot_vel: 1.0 #1.0
  min_rot_vel: -1.0 #0.4

  # trans_stopped_vel: 0.1
  # rot_stopped_vel: 5

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05 # 0.05
  xy_goal_tolerance: 0.1 # 0.10
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.7 # 1.7
  sim_granularity: 0.025 #0.025
  angular_sim_granularity: 0.02
  vx_samples: 3 # 3
  vy_samples: 10 # 10
  vtheta_samples: 20 # 20

  # Trajectory Scoring Parameters
  path_distance_bias: 1.0 # 32.0
  goal_distance_bias: 24 # 24.0
  occdist_scale: 0.01 # 0.01
  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.2 # 0.2
  scaling_speed: 0.25 # 0.25
  max_scaling_factor: 0.2 # 0.2
  # publish_cost_grid: false        #false

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 # 0.05

  # Debugging
  # publish_traj_pc : true
  # publish_cost_grid_pc: true

  holonomic_robot: false
