base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  old_navfn_behavior: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false

  allow_unknown: false

  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.0

  outline_map: false
