global_costmap:
  global_frame: world
  robot_base_frame: body
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  transform_tolerance: 0.5
  resolution: 0.1
  width: 500
  height: 500
