local_costmap:
  global_frame: world
  robot_base_frame: body
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  transform_tolerance: 0.3
  width: 20
  height: 20
  resolution: 0.1
