controller_frequency: 10.0
controller_patience: 20.0

planner_frequency: 0.5
planner_patience: 20.0

oscillation_timeout: 0.0
oscillation_distance: 0.2

shutdown_costmaps: false
# conservative_reset_dist: 3.0
# recovery_behavior_enabled: true
# clearing_rotation_allowed: true

max_planning_retries: -1.0
